id = "t4t5.windows98"
name = "Windows 98 Theme"
description = "Browse your calendar like it’s 1998!"
min_rencal_version = "0.8.0"

[[contributes.fonts]]
family = "Pixelated MS Sans Serif"
file = "fonts/ms_sans_serif.woff2"

[[contributes.fonts]]
family = "Pixelated MS Sans Serif"
file = "fonts/ms_sans_serif_bold.woff2"
weight = 700

[[contributes.themes]]
id = "windows98"
name = "Windows 98"
css = "themes/windows98.css"
appearance = "light"
